github: [metadata]
theme: minima
kramdown:
   input: GFM
   hard_wrap: false
gems:
   - jekyll-coffeescript
   - jekyll-paginate
title: Jindřich's blog
# decription: >
#baseurl: "https://jlibovicky.github.io"
#twitter_username: jlibovicky
github_username: jlibovicky
