github: [metadata]
theme: minima
markdown: kramdown
kramdown:
   input: GFM
   hard_wrap: false
   auto_ids: true
   syntax_highlighter: rouge
gems:
   - jekyll-coffeescript
   - jekyll-paginate
title: Jindřich's blog
# decription: >
#baseurl: "https://jlibovicky.github.io"
#twitter_username: jlibovicky
github_username: jlibovicky
