github: [metadata]
theme: minima
markdown: kramdown
kramdown:
   input: GFM
   hard_wrap: false
   auto_ids: true
   syntax_highlighter: rouge
gems:
   - jekyll-coffeescript
   - jekyll-paginate
   - jekyll-seo-tag
title: Jindřich's blog
decription: A blog on deep learning and natural language processing.
baseurl: "https://jlibovicky.github.io"
twitter_username: jlibovicky
github_username: jlibovicky
social:
   - https://www.linkedin.com/in/jind%C5%99ich-libovick%C3%BD-13281046/
   - https://twitter.com/jlibovicky
   - http://ufal.mff.cuni.cz/jindrich-libovicky
